import { writable } from 'svelte/store';
import type { IBase } from '$lib/utils';

export interface ICurrency extends IBase {
	value?: number;
}

export const currencies = writable<ICurrency[]>([
	{ id: 'AED' },
	{ id: 'AMD' },
	{ id: 'ARS' },
	{ id: 'AUD' },
	{ id: 'AZN' },
	{ id: 'BDT' },
	{ id: 'BGN' },
	{ id: 'BOB' },
	{ id: 'BRL' },
	{ id: 'BYN' },
	{ id: 'CAD' },
	{ id: 'CHF' },
	{ id: 'CLP' },
	{ id: 'CNY' },
	{ id: 'CZK' },
	{ id: 'DKK' },
	{ id: 'EGP' },
	{ id: 'ETB' },
	{ id: 'EUR' },
	{ id: 'GBP' },
	{ id: 'GEL' },
	{ id: 'HKD' },
	{ id: 'ILS' },
	{ id: 'INR' },
	{ id: 'IQD' },
	{ id: 'IRR' },
	{ id: 'JOD' },
	{ id: 'JPY' },
	{ id: 'KGS' },
	{ id: 'KRW' },
	{ id: 'KZT' },
	{ id: 'LBP' },
	{ id: 'MDL' },
	{ id: 'MKD' },
	{ id: 'MNT' },
	{ id: 'MXN' },
	{ id: 'NGN' },
	{ id: 'PHP' },
	{ id: 'PLN' },
	{ id: 'PKR' },
	{ id: 'QAR' },
	{ id: 'RON' },
	{ id: 'RUB' },
	{ id: 'SAR' },
	{ id: 'SDG' },
	{ id: 'SEK' },
	{ id: 'SYP' },
	{ id: 'THB' },
	{ id: 'TJS' },
	{ id: 'TMT' },
	{ id: 'TRY' },
	{ id: 'TWD' },
	{ id: 'UAH' },
	{ id: 'USD' },
	{ id: 'UZS' },
	{ id: 'VND' },
	{ id: 'XAF' },
	{ id: 'XOF' },
	{ id: 'ZAR' },
	{ id: 'ZMW' }
]);
